// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using john_moreau_MidTerm.Models;

#nullable disable

namespace john_moreau_MidTerm.Migrations
{
    [DbContext(typeof(SportsContext))]
    [Migration("20231029065645_Technicians")]
    partial class Technicians
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("john_moreau_MidTerm.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateAdded")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(8,2)");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Code = "TRNY",
                            DateAdded = "10/28/2023 at 11:56 PM",
                            Name = "Tournament Master 1.0",
                            Price = 4.99m,
                            ReleaseDate = new DateTime(2018, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProductId = 2,
                            Code = "LEAG10",
                            DateAdded = "10/28/2023 at 11:56 PM",
                            Name = "League Scheduler 1.0",
                            Price = 4.99m,
                            ReleaseDate = new DateTime(2019, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProductId = 3,
                            Code = "LEAGD10",
                            DateAdded = "10/28/2023 at 11:56 PM",
                            Name = "League Scheduler Deluxe 1.0",
                            Price = 7.99m,
                            ReleaseDate = new DateTime(2019, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ProductId = 4,
                            Code = "PS5",
                            DateAdded = "10/28/2023 at 11:56 PM",
                            Name = "Play Station 5",
                            Price = 699.99m,
                            ReleaseDate = new DateTime(2020, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("john_moreau_MidTerm.Models.Technician", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DateAdded")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Technicians");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateAdded = "",
                            Email = "email@email.com",
                            Name = "John Moreau",
                            Phone = "509-559-5959"
                        },
                        new
                        {
                            Id = 2,
                            DateAdded = "",
                            Email = "robin@wwcc.com",
                            Name = "Robin Greene",
                            Phone = "509-955-9595"
                        },
                        new
                        {
                            Id = 3,
                            DateAdded = "",
                            Email = "alison@email.com",
                            Name = "Alison Diaz",
                            Phone = "509-555-0443"
                        },
                        new
                        {
                            Id = 4,
                            DateAdded = "",
                            Email = "andrew@email.com",
                            Name = "Andrew Wilson",
                            Phone = "509-555-0449"
                        },
                        new
                        {
                            Id = 5,
                            DateAdded = "",
                            Email = "gina@email.com",
                            Name = "Gina Fiori",
                            Phone = "509-555-0459"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
